/**
 * Export Module
 * Handles vocabulary and conversation export functionality
 */

const ExportManager = {
    /**
     * Export conversation to text file
     */
    exportConversation() {
        const conversation = ConversationGenerator.currentConversation;

        if (conversation.length === 0) {
            Utils.showToast('No conversation to export', 'error');
            return;
        }

        // Get conversation metadata
        const topic = document.getElementById('topic').value;
        const difficulty = document.querySelector('input[name="difficulty"]:checked')?.value || 'easy';
        const tone = document.getElementById('tone').value;
        const topicName = TopicNames[topic] || topic;

        // Build export content
        let content = '';
        content += '='.repeat(50) + '\n';
        content += 'VOCABULARY BOT - Generated Conversation\n';
        content += '='.repeat(50) + '\n\n';
        content += `Topic: ${topicName}\n`;
        content += `Difficulty: ${Utils.capitalizeFirst(difficulty)}\n`;
        content += `Tone: ${Utils.capitalizeFirst(tone)}\n`;
        content += `Generated: ${new Date().toLocaleString()}\n\n`;
        content += '-'.repeat(50) + '\n';
        content += 'CONVERSATION\n';
        content += '-'.repeat(50) + '\n\n';

        // Add conversation lines
        conversation.forEach(line => {
            const speakerLabel = line.speaker === 'A' ? 'Speaker A' : 'Speaker B';
            content += `${speakerLabel}: ${line.text}\n\n`;
        });

        // Add vocabulary section if available
        const details = ConversationGenerator.vocabularyDetails;
        const vocabWords = Object.keys(details);

        if (vocabWords.length > 0) {
            content += '-'.repeat(50) + '\n';
            content += 'VOCABULARY USED\n';
            content += '-'.repeat(50) + '\n\n';

            vocabWords.forEach(word => {
                const data = details[word];
                content += `${word} (${data.type})\n`;
                content += `  Definition: ${data.definition}\n`;
                if (data.phonetic) content += `  Phonetic: ${data.phonetic}\n`;
                if (data.examples && data.examples[0]) content += `  Example: "${data.examples[0]}"\n`;
                content += '\n';
            });
        }

        content += '='.repeat(50) + '\n';
        content += 'Generated by Vocabulary Bot\n';
        content += '='.repeat(50) + '\n';

        // Generate filename with timestamp
        const timestamp = new Date().toISOString().slice(0, 10);
        const filename = `conversation-${topic}-${difficulty}-${timestamp}.txt`;

        this.downloadFile(content, filename, 'text/plain');
        Utils.showToast('Conversation exported successfully!');
    },

    /**
     * Export vocabulary to CSV file (kept for potential future use)
     */
    exportVocabulary() {
        const details = ConversationGenerator.vocabularyDetails;
        const words = [];

        Object.entries(details).forEach(([word, data]) => {
            words.push({
                word,
                type: data.type,
                definition: data.definition,
                phonetic: data.phonetic || '',
                synonyms: data.synonyms?.join(', ') || '',
                examples: data.examples?.join(' | ') || ''
            });
        });

        if (words.length === 0) {
            Utils.showToast('No vocabulary to export', 'error');
            return;
        }

        // Create CSV
        const headers = ['Word', 'Type', 'Definition', 'Phonetic', 'Synonyms', 'Examples'];
        const csv = [
            headers.join(','),
            ...words.map(w => [
                `"${w.word}"`,
                `"${w.type}"`,
                `"${w.definition}"`,
                `"${w.phonetic}"`,
                `"${w.synonyms}"`,
                `"${w.examples}"`
            ].join(','))
        ].join('\n');

        this.downloadFile(csv, 'vocabulary.csv', 'text/csv');
        Utils.showToast('Vocabulary exported successfully!');
    },

    /**
     * Copy conversation to clipboard
     */
    async copyConversation() {
        const conversation = ConversationGenerator.currentConversation;
        if (conversation.length === 0) return;

        const text = ConversationGenerator.getPlainText();
        try {
            await navigator.clipboard.writeText(text);
            Utils.showToast('Conversation copied to clipboard!');
        } catch (err) {
            Utils.showToast('Failed to copy', 'error');
        }
    },

    /**
     * Download a file
     */
    downloadFile(content, filename, mimeType) {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    }
};
